### ISSUE TITLE
fatal error: 'google/protobuf/compiler/objectivec/objectivec_helpers.h' file not found

### ISSUE THREAD

**Issue by 0x5143** [grpc/homebrew-grpc#29]
yunjingdeMacBook-Pro:grpc--git Neil$ curl -fsSL https://goo.gl/getgrpc | bash -
openssl is already installed
Warning: Already tapped!
google-protobuf is already installed
==> Installing grpc from grpc/homebrew-grpc
==> Cloning https://github.com/grpc/grpc.git
Updating /Library/Caches/Homebrew/grpc--git
==> Checking out branch master
==> make install install_grpc_csharp_ext prefix=/usr/local/Cellar/grpc/HEAD
src/compiler/objective_c_generator.cc:41:10: fatal error: 'google/protobuf/compiler/objectivec/objectivec_helpers.h' file not found
# include <google/protobuf/compiler/objectivec/objectivec_helpers.h>

```
     ^
```

2 errors generated.
make: **\* [objs/opt/src/compiler/objective_c_generator.o] Error 1
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Module:0x007fd558996238>::Grpc (TypeError)
    from /usr/local/Library/Homebrew/build.rb:181:in`rescue in <main>'
    from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: Suspicious failure

**Comment by tbetbetbe** [comment]
- can you try doing a `brew update` and running this again ?
  It looks as if you somehow you're picking up an older version of the grpc tap.

**Comment by 0x5143** [comment]
Latest release hava fixed it.
