### ISSUE TITLE
PHP unit tests breaks against linuxbrew installation of grpc core

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/homebrew-grpc#39]
So far, my PHP testing w/ homebrew had focused on the Hello World, and Route Guide application on the `grpc-common` side. And they work.

But if I run the [PHP unit tests](https://github.com/grpc/grpc/tree/master/src/php) against the homebrew installation of grpc core, I got this error:

```
Starting test 'CallTest::testAddEmptyMetadata'.
.
Starting test 'CallTest::testAddSingleMetadata'.
.
Starting test 'CallTest::testAddMultiValueMetadata'.
.
Starting test 'CallTest::testAddSingleAndMultiValueMetadata'.
.
Starting test 'EndToEndTest::testSimpleRequestBody'.
.
Starting test 'EndToEndTest::testClientServerFullRequestResponse'.
.
Starting test 'SecureEndToEndTest::testSimpleRequestBody'.
php: symbol lookup error: /home/stanleycheung/.linuxbrew/lib/libgrpc.so.0: 
undefined symbol: SSL_CTX_set_alpn_select_cb
```

This does not seem to be release-related. The current grpc version being installed by homebrew is 0.9.0 but it does not seem to matter. I tried 0.9.0, 0.9.1 or upstream/master and they all fail the same way. I also made sure the PHP extension code is at the same level as core.

This error also does not happen if I compile grpc from source.

What I suspect is that there's a subtle difference on how openssl is compiled/installed. If I compile grpc from source, openssl is compiled from `grpc/third_party/openssl` (version 1.0.2a). If I install grpc via homebrew, openssl is installed via the dependency `depends_on "openssl"` (version 1.0.2c).

**Comment by murgatroid99** [comment]
That error looks related to not having the new version of OpenSSL. Perhaps you are linking against the correct version of OpenSSL but dynamically loading the system OpenSSL.

**Comment by stanley-cheung** [comment]
Thanks Michael, and Tim. Your tips work - the PHP unit tests work now, over homebrew, if I run this instead:

```
~/grpc/src/php$ LD_LIBRARY_PATH=$BREWHOME/lib ./bin/run_tests.sh 
```

I will investigate if I can add a linker flag at the compile step.

**Comment by stanley-cheung** [comment]
Investigated this some more and don't seem to be able to find a better solution than using `LD_LIBRARY_PATH` (although it's considered a bad practice).

But I did narrow it down to the exact mismatch at runtime. The system installed version of openssl (1.0.1 for my testing) was indeed being dynamically loaded at runtime, hence the error. There are 2 more ways to get around that by either adding a path to `/etc/ld.so.conf`, or just re-aliasing the library under `/usr/lib/x86_64-linux-gnu` but that seems really hacky. 

Still believe that some kind of linker flags are missing

**Comment by stanley-cheung** [comment]
Looks like it has nothing to do with how grpc is being compiled - it's the PHP binaries itself that's loading the system installed version of openssl:

```
stanleycheung@stanleycheung-test:~$ echo '<?php phpinfo(); ?>' | php 2>&1 | grep -i ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.1e 11 Feb 2013
OpenSSL Header Version => OpenSSL 1.0.1e 11 Feb 2013
OpenSSL support => enabled

stanleycheung@stanleycheung-test:~$ echo '<?php phpinfo(); ?>' | LD_LIBRARY_PATH=$BREWHOME/lib php 2>&1 | grep -i ssl
php: /home/stanleycheung/.linuxbrew/lib/libssl.so.1.0.0: no version information available (required by php)
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2c 12 Jun 2015
OpenSSL Header Version => OpenSSL 1.0.1e 11 Feb 2013
OpenSSL support => enabled
```

**Comment by stanley-cheung** [comment]
The strange thing is that `ldd` seems to indicate that the library is linked correctly

```
stanleycheung@stanleycheung-test:~/grpc/src/php$ ldd -v /home/stanleycheung/.linuxbrew/lib/libgrpc.so.0
    linux-vdso.so.1 =>  (0x00007ffd6a926000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0fbd2c7000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0fbd045000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0fbce2d000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0fbcc11000)
    libssl.so.1.0.0 => /home/stanleycheung/.linuxbrew/lib/libssl.so.1.0.0 (0x00007f0fbc9a0000)
    libcrypto.so.1.0.0 => /home/stanleycheung/.linuxbrew/lib/libcrypto.so.1.0.0 (0x00007f0fbc552000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0fbc34e000)
    libgpr.so.0 => /home/stanleycheung/.linuxbrew/lib/libgpr.so.0 (0x00007f0fbc142000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0fbbdb6000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f0fbd734000)
```

The `libssl.so.1.0.0` and `libcrypto.so.1.0.0` under the `/home/stanleycheung/.linuxbrew/lib` directory is definitely version 1.0.2

**Comment by murgatroid99** [comment]
Now I remember. The problem is that if you dynamically link against `libssl` and `libcrypto`, the system libraries are already loaded when PHP starts up, so it never attempts to load the versions that the library is linked against.

**Comment by stanley-cheung** [comment]
Interestingly, this error

```
Starting test 'SecureEndToEndTest::testSimpleRequestBody'.
php: symbol lookup error: /home/stanleycheung/.linuxbrew/lib/libgrpc.so.0:
undefined symbol: SSL_CTX_set_alpn_select_cb
```

only happens on linuxbrew. The unit tests run fine on a homebrew grpc install on Mac.

**Comment by stanley-cheung** [comment]
This becomes irrelevant now that we have a [gRPC Debian package](https://packages.debian.org/sid/libgrpc-dev). Also will be working on a RPM package for redhat.
