### ISSUE TITLE
Update grpc homebrew formula to 0.9.1

### ISSUE THREAD

**Issue by jtattermusch** [grpc/homebrew-grpc#40]
Looks like it somehow slipped and grpc formula is still pointing to 0.9.0 version. We should update to 0.9.1. 
Btw, it would be great if we could test this change with jenkins ;-)

https://github.com/grpc/homebrew-grpc/blob/master/Formula/grpc.rb

**Comment by stanley-cheung** [comment]
Related to grpc/grpc#1883

**Comment by stanley-cheung** [comment]
Tested a fresh install of grpc and grpc-php formula (version 0.9.1) in both Mac and Linux.
