### ISSUE TITLE
in china : Failed to connect to 2404:6800:4008:c04::52: No route to host

### ISSUE THREAD

**Issue by i5ting** [grpc/homebrew-grpc#56]
➜  grpc  brew install grpc
==> Installing grpc from grpc/homebrew-grpc
Error: Operation already in progress for xz
Another active Homebrew process is already using xz.
Please wait for it to finish or terminate it to continue.
➜  grpc  brew install grpc
==> Installing grpc from grpc/homebrew-grpc
==> Installing grpc dependency: google-protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-alpha-3.tar.gz
Already downloaded: /Library/Caches/Homebrew/google-protobuf-3.0.0-alpha-3.tar.gz
==> ./autogen.sh

Google Test not present.  Fetching gtest-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (7) Failed to connect to 2404:6800:4008:c04::52: No route to host

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/grpc/homebrew-grpc/issues

**Comment by tbetbetbe** [comment]
The autogen step of the build of the protobuf dependency is failing
- it's trying to download gtest and install it,  that download is not succeeding

That's going to be related to the network you are running on.
I'm going to close this, as it's not something that we can fix.
