### ISSUE TITLE
homebrew nodejs install failure on jenkins 

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/homebrew-grpc#63]
This is our regular Jenkins build on macos, installing gRPC nodejs via homebrew. Basically running this command: `curl -fsSL https://goo.gl/getgrpc | bash -s nodejs`, and it's giving this error.

I run the same command on my Mac machine and it runs fine. Could be an issue specific to the machine grpc-mac-node2?

https://grpc-testing.appspot.com/job/gRPC_distribution/dist_channel=homebrew,language=nodejs,platform=macos/lastBuild/console

```
installing grpc nodejs
npm ERR! tar.unpack untar error /Users/jenkinsnode2/.npm/grpc/0.11.1/package.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--global" "grpc"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/local/lib/node_modules/grpc
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/grpc'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/grpc']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/grpc',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/grpc',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /jenkins/workspace/gRPC_distribution/dist_channel/homebrew/language/nodejs/platform/macos/npm-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

The homebrew installation script has already gone past the base grpc installation and is basically running this command

```
CXXFLAGS=-I${brew_root}/include LDFLAGS=-L${brew_root}/lib npm install --global grpc
```

This is supposed to be the 0.11.0 release.

**Comment by murgatroid99** [comment]
I haven't touched the release branch in weeks. The problem in that particular error is caused by trying to globally install the gRPC Node package in `/usr/local/lib/` without using `sudo`.You probably don't see it because you're using nvm, which puts Node in your home directory. I don't know why this failure would have just started, though. Maybe that Mac machine stopped using nvm for some reason.

**Comment by stanley-cheung** [comment]
Ah, i think this is an issue specific to grpc-mac-node2 then. Coz in grpc-mac-node1 the build is green.

https://grpc-testing.appspot.com/job/gRPC_distribution/dist_channel=homebrew,language=nodejs,platform=macos/647/console

**Comment by stanley-cheung** [comment]
Yes, `nvm` is missing from grpc-mac-node2. I installed it and has restarted the build. See if that helps.

https://grpc-testing.appspot.com/job/gRPC_distribution/663/

**Comment by stanley-cheung** [comment]
The entire build is back to green now. https://grpc-testing.appspot.com/job/gRPC_distribution/664/. Closing this.
