### ISSUE TITLE
Installing on brew package on Linux fails due to pkg-config problem?

### ISSUE THREAD

**Issue by jgeewax** [grpc/homebrew-grpc#69]
Following the instructions to install on Wheezy without jessie backports fails:

``` sh
$ brew tap grpc/grpc
==> Tapping grpc/grpc
Cloning into '/home/jjg/.linuxbrew/Library/Taps/grpc/homebrew-grpc'...
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
Tapped 2 formulae (39 files, 296K)
$ brew install --without-libgrpc grpc
==> Installing grpc from grpc/homebrew-grpc
==> Tapping homebrew/dupes
Cloning into '/home/jjg/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Tapped 0 formulae (102 files, 640K)
==> Installing dependencies for grpc/grpc/grpc: makedepend, zlib, openssl, pkg-config, xz, homebrew/dupes/m4, autoconf, automake, libtool, google-protobuf
==> Installing grpc/grpc/grpc dependency: makedepend
Error: /home/jjg/.linuxbrew/opt/pkg-config not present or broken
Please reinstall pkg-config. Sorry :(
```

**Comment by murgatroid99** [comment]
Linuxbrew is not the recommended way of installing gRPC. That being said, it might help to add `pkg-config` as a dependency.

**Comment by jgeewax** [comment]
OK, so should we basically say "don't do this" ? I thought @tbetbetbe mentioned ti was "one of the ways" to get gRPC.

**Comment by murgatroid99** [comment]
It's not entirely unsupported. The README for this repo is more specific. But we would prefer that you use the debian package because it is more well supported.

**Comment by jgeewax** [comment]
Gotcha. So probably best to say "this just isn't a thing we're trying to do via Linuxbrew" and "we think you should install on Linux some other way" -- yea?

**Comment by murgatroid99** [comment]
That looks right to me. And I also believe that the README essentially says that in the note about Linuxbrew.

**Comment by jgeewax** [comment]
Yep -- SGTM. Sorry for the noise!
