### ISSUE TITLE
grpc 0.14 not updated in homebrew

### ISSUE THREAD

**Issue by GuoJing** [grpc/homebrew-grpc#76]
Maybe we need a new version of grpc 0.13, some change and bug fix is very important to us.

thanks.

**Comment by stanley-cheung** [comment]
grpc 0.13 hasn't been released yet. Will update as soon as that's done.

**Comment by jamel** [comment]
What about version 0.13.1 which is released https://github.com/grpc/grpc/releases/tag/release-0_13_1 already?

**Comment by jtattermusch** [comment]
Grpc 0.14.2 will be out soon so I'll just kidnap this issue for that purpose.

**Comment by jtattermusch** [comment]
https://github.com/grpc/homebrew-grpc/pull/81

**Comment by stanley-cheung** [comment]
1.0.0 now
