### ISSUE TITLE
Patching Error on Mac 10.10.5

### ISSUE THREAD

**Issue by lifeiteng** [grpc/homebrew-grpc#78]
==> Installing grpc from grpc/homebrew-grpc
==> Installing grpc/grpc/grpc dependency: google-protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-beta-2.tar.gz
Already downloaded: /Library/Caches/Homebrew/google-protobuf-3.0.0-beta-2.tar.gz
==> Downloading https://raw.githubusercontent.com/grpc/homebrew-grpc/master/patches/google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch
Already downloaded: /Library/Caches/Homebrew/google-protobuf--patch-47cbaaf7e782b09edb5dcf10ff6b7892af8f506df4d82f71877957de3552afa4.patch
==> Patching
patching file python/google/protobuf/pyext/message.cc
Hunk #1 FAILED at 340.
1 out of 1 hunk FAILED -- saving rejects to file python/google/protobuf/pyext/message.cc.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/google-protobuf--patch20160226-33331-e8ktnb/google_protobuf_4472b4a_Fixed-assignment-syntax-error.patch

**Comment by Taik** [comment]
:+1: I'm getting the same on my machines.

**Comment by twreid** [comment]
I am getting this error as well. If more info is needed I am willing to provide what I can to help get this fixed.

**Comment by zuyu** [comment]
@stanley-cheung Please close this issue. Thanks!
