### ISSUE TITLE
Doesn't install plugins on macOS sierra 

### ISSUE THREAD

**Issue by mehrdadrad** [grpc/homebrew-grpc#95]
I tried the below commands on macOS sierra 10.12.2 but the plugins didn't install as I had errors:

curl -fsSL https://goo.gl/getgrpc | bash -s -- --with-plugins
brew install --with-plugins grpc

```
sh-3.2# protoc --go_out=plugins=grpc:. *.proto
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

I had to compile the protoc-gen-go manually to fix

**Comment by MilosSimic** [comment]
I had the same problem, i've resolved it like this:
1) go get -u github.com/golang/protobuf/protoc-gen-go
2) copy protoc-gen-go from bin folder from go workspace to /usr/local/bin/

note: i've installed grpc and protobuf using homebrew

protoc need to know where protoc-gen-go is, alternatively (and probably better) is to:
1) go get -u github.com/golang/protobuf/protoc-gen-go
2) export GOPATH=$HOME/go
3) PATH=$PATH:$GOPATH/bin

then protoc --go_out=plugins=grpc:. *.proto will do its job

**Comment by stanley-cheung** [comment]
The "grpc" and "protobuf" formulas are being maintained at the main homebrew-core repo now. There is no need to add this grpc/grpc tap anymore.

brew install grpc and brew install protobuf should just work.

**Comment by panyaxbo** [comment]
> I had the same problem, i've resolved it like this:
> 
> 1. go get -u github.com/golang/protobuf/protoc-gen-go
> 2. copy protoc-gen-go from bin folder from go workspace to /usr/local/bin/
> 
> note: i've installed grpc and protobuf using homebrew
> 
> protoc need to know where protoc-gen-go is, alternatively (and probably better) is to:
> 
> 1. go get -u github.com/golang/protobuf/protoc-gen-go
> 2. export GOPATH=$HOME/go
> 3. PATH=$PATH:$GOPATH/bin
> 
> then protoc --go_out=plugins=grpc:. *.proto will do its job

You really save my day

**Comment by Prosp3r** [comment]
> I had the same problem, i've resolved it like this:
> 
> 1. go get -u github.com/golang/protobuf/protoc-gen-go
> 2. copy protoc-gen-go from bin folder from go workspace to /usr/local/bin/
> 
> note: i've installed grpc and protobuf using homebrew
> 
> protoc need to know where protoc-gen-go is, alternatively (and probably better) is to:
> 
> 1. go get -u github.com/golang/protobuf/protoc-gen-go
> 2. export GOPATH=$HOME/go
> 3. PATH=$PATH:$GOPATH/bin
> 
> then protoc --go_out=plugins=grpc:. *.proto will do its job

This(copying to /usr/local/bin) worked like a charm. Thanks for laying it out.

**Comment by tianly123** [comment]
nice! love you
